# Generated by Django 2.2.14 on 2020-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='satus',
            field=models.TextField(blank=True),
        ),
    ]
