# Generated by Django 2.2.14 on 2020-11-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201119_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatau', models.CharField(max_length=100)),
                ('ini_juga', models.IntegerField(default=1)),
            ],
        ),
    ]
